### ISSUE TITLE
Walkthrough needed

### ISSUE THREAD

**Issue by uo-lca** [uo-lca/CalRecycleLCA#256]
Need to write a walkthrough page in the Wiki for (a) generating new scenarios and (b) scenario analysis.

**Comment by bkuczenski** [comment]
This was done in time for release:
https://github.com/uo-lca/uo-lca.github.io/wiki/Walkthrough-I:-Scenario-modeling
https://github.com/uo-lca/uo-lca.github.io/wiki/Walkthrough-II:-Improper-Disposal
